### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by beaniekun** [nikolamilosevic86/Marvin#2]
There is no Marvin.jar file but the readme says to run it? My terminal is saying "Error: Unable to access jarfile Marvin.jar" Please advise

**Comment by nikolamilosevic86** [comment]
Hello,

Marvin.jar file needs to be created either by compiling the code on the repository, or you can use the one that is already created and packed in one of the releases: https://github.com/nikolamilosevic86/Marvin/releases 

Also, make sure you have installed data sources that you use Marvin with (MetaMap, Wordnet or DBPedia, or provide SKOS vocabulary in the right format). 

Hope that helps.

**Comment by saieccles** [comment]
So in those releases I'm not seeing a Marvin.jar file.

If I want to create one myself I have to run a command of the form:

jar cf jar-file input-file(s)

which files do I need to input?

Thanks
